import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
 * Obsyncth - Seamless Obsidian-Syncthing Integration
 * Copyright (c) 2024-2025 Reza Mir
 * 
 * This is a generated/bundled file by esbuild
 * Source code: https://github.com/muxammadreza/Obsyncth
 */
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}